### ISSUE TITLE
部署后的项目提示“未登录或已登录超时，请重新登录”，本地没有问题

### ISSUE THREAD

**Issue by gpqhl0071** [rymcu/nebula#115]
**问题描述**:
在本地开发环境中，一切运行正常。然而，当我将项目部署到服务器后，访问页面时总是提示“未登录或已登录超时，请重新登录”。以下是问题的详细描述和相关信息：

**环境信息**:

**问题截图**:
<img width="1506" alt="Snipaste_2024-07-05_15-42-23" src="https://github.com/rymcu/nebula/assets/8787216/ffd46d5c-6643-45b4-8a49-855160686bc1">

**重现步骤**:
1. 在本地环境中运行项目，登录并访问相关页面，一切正常。
2. 将项目部署到服务器。
3. 访问部署后的项目页面，提示“未登录或已登录超时，请重新登录”。

**预期结果**:
在服务器上部署后，访问页面应该与本地环境一样，正常显示内容，而不是提示登录超时。

**实际结果**:
在服务器上访问页面时，总是提示“未登录或已登录超时，请重新登录”。

非常感谢您的帮助！

**Comment by ronger-x** [comment]
部署到服务器时需要配置 nginx 代理来让前端正确请求后端接口
`/api->/forest/api/v1`
