### ISSUE TITLE
启动报错，但是不知道是什么原因

### ISSUE THREAD

**Issue by lucas5-code** [rymcu/nebula#117]
错误日志：
0|nebula  |   data: { code: 401, message: '签名错误', success: false } }
0|nebula  |  ERROR  Cannot set headers after they are sent to the client

前端api.config.js 配置文件如下
cat config/api.config.js 
import {NODE_ENV} from '../environment'

const apisMap = {
  development: {
    FE: 'http://172.29.47.233:3000',
    BASE: 'http://172.29.47.233:8099/forest',
    CDN: '',
    PROXY: '/proxy',
    SOCKET: 'http://172.29.47.233:3000/ws',
    GRAVATAR: 'https://static.rymcu.com/avatar',
    VDITOR: 'https://static.rymcu.com/vditor@3.10.3/',
    VDITOR_CSS: 'https://static.rymcu.com/vditor@3.10.3/dist/css/content-theme'
  },
  test: {
    FE: 'https://rymcu.com',
    BASE: 'http://172.29.47.233:8099/forest',
    CDN: 'https://static.rymcu.com',
    PROXY: 'https://static.rymcu.com/proxy',
    SOCKET: 'https://rymcu.com/wss',
    GRAVATAR: 'https://static.rymcu.com/avatar',
    VDITOR: 'https://static.rymcu.com/vditor@3.10.3/',
    VDITOR_CSS: 'https://static.rymcu.com/vditor@3.10.3/dist/css/content-theme'
  },
  production: {
    FE: 'https://rymcu.com',
    BASE: 'http://172.29.47.233:8099/forest',
    CDN: 'https://static.rymcu.com',
    PROXY: 'https://static.rymcu.com/proxy',
    SOCKET: 'https://rymcu.com/wss',
    GRAVATAR: 'https://static.rymcu.com/avatar',
    VDITOR: 'https://static.rymcu.com/vditor@3.10.3/',
    VDITOR_CSS: 'https://static.rymcu.com/vditor@3.10.3/dist/css/content-theme'
  }
}

**Comment by ronger-x** [comment]
目前提供的信息无法定位问题, 看看[提问的智慧](https://rymcu.com/article/80)会给予你许多帮助。

**Comment by lucas5-code** [comment]
你好已经解决了，问题是指定dev环境外面加了双引号，还有FE配置改为本地地址。谢谢你的回复，希望能帮到其他人
