### ISSUE TITLE
项目启动后无法访问

### ISSUE THREAD

**Issue by LiManyuan663** [rymcu/nebula#118]
```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 00007FF6FBCDBA4B node::SetCppgcReference+16011
 2: 00007FF6FBC453F8 SSL_get_quiet_shutdown+92008
 3: 00007FF6FC7D2D81 v8::Isolate::ReportExternalAllocationLimitReached+65
 4: 00007FF6FC7BFB86 v8::Function::Experimental_IsNopFunction+2918
 5: 00007FF6FC60B830 v8::internal::StrongRootAllocatorBase::StrongRootAllocatorBase+31552
 6: 00007FF6FC6054FD v8::internal::StrongRootAllocatorBase::StrongRootAllocatorBase+6157
 7: 00007FF6FC600D95 v8::internal::ThreadIsolation::JitPageReference::Size+190789
 8: 00007FF6FBF7A30D BIO_ssl_shutdown+189
error Command failed with exit code 134.
```
您好，项目在http://localhost:3000/启动之后，页面无法加载，报这个错是什么原因。

**Comment by ronger-x** [comment]
错误信息提示的很清楚, 内存溢出

当你遇到**使用搜索引擎、查阅相关文档、进行 Debug**（如果没有做过上述操作的话，请立刻去做）也无法解决的问题的时候，你可能会向别人求助。现在就来讲讲如何正确提问。

当你进行提问时，请保证你准确提供了以下信息：

- 准确的描述你的需求和实际问题情况。
- 准确的描述你所在的平台的信息。例如：
  - 开发板型号
  - 运行程序( IDE 等)名称及其版本
  - Windows/Linux/MacOS 任一平台及其版本
  - 依赖的类库及其版本
- 提供你的源代码，将源代码包括开发环境完整上传至源码托管平台（如 Github）。
- 提供你的完整日志、异常输出。

如果你在社区提问，请在你的标题也简略的包含问题描述和平台信息。例如 `nodejs 18`  `win10` 运行程序时，抛出异常

如果你想学习更多关于提问的方法、技巧、礼仪，看看[提问的智慧](https://rymcu.com/article/80)会给予你许多帮助。


>   可能有用的信息:   https://geekflare.com/fix-javascript-heap-out-of-memory-error/

**Comment by LiManyuan663** [comment]
> 错误信息提示的很清楚, 内存溢出
> 
> 当你遇到**使用搜索引擎、查阅相关文档、进行 Debug**（如果没有做过上述操作的话，请立刻去做）也无法解决的问题的时候，你可能会向别人求助。现在就来讲讲如何正确提问。
> 
> 当你进行提问时，请保证你准确提供了以下信息：
> 
> * 准确的描述你的需求和实际问题情况。
> * 准确的描述你所在的平台的信息。例如：
>   
>   * 开发板型号
>   * 运行程序( IDE 等)名称及其版本
>   * Windows/Linux/MacOS 任一平台及其版本
>   * 依赖的类库及其版本
> * 提供你的源代码，将源代码包括开发环境完整上传至源码托管平台（如 Github）。
> * 提供你的完整日志、异常输出。
> 
> 如果你在社区提问，请在你的标题也简略的包含问题描述和平台信息。例如 `nodejs 18` `win10` 运行程序时，抛出异常
> 
> 如果你想学习更多关于提问的方法、技巧、礼仪，看看[提问的智慧](https://rymcu.com/article/80)会给予你许多帮助。
> 
> > 可能有用的信息:   https://geekflare.com/fix-javascript-heap-out-of-memory-error/

您好。我使用的是内存16GB的笔记本电脑，我并没有运行其他程序，后端已经部署到服务器上，我想出现内存溢出的问题是不应该的。
除了内存溢出的报错，控制台还有其他报错：
```
connect ECONNREFUSED ::1:3000                                                                                                                 10:22:54  

    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16)
undefined                                                                                                                                     10:22:54
undefined  
```
```
Request failed with status code 404                                                                                                           10:22:56

    at createError (node_modules\axios\lib\core\createError.js:16:15)
    at settle (node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (node_modules\axios\lib\adapters\http.js:269:11)
    at IncomingMessage.emit (node:events:536:35)
    at endReadableNT (node:internal/streams/readable:1698:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
undefined                                                                                                                                     10:22:56
undefined                                                                                                                                     10:22:56
undefined                                                                                                                                     10:22:56  
undefined   
```
对于路由我已经在api.config,js中进行配置，
```
  development: {
    FE: 'http://localhost:3000',
    BASE: 'http://localhost:8080/api/v1',
    CDN: '',
    PROXY: '/proxy',
    SOCKET: 'http://localhost:3000/ws',
    GRAVATAR: 'https://static.rymcu.com/avatar',
    VDITOR: 'https://static.rymcu.com/vditor@3.10.3/',
    VDITOR_CSS: 'https://static.rymcu.com/vditor@3.10.3/dist/css/content-theme'
  },
```
具体的请求也按照`forest`项目中的路由进行了修改：
![image](https://github.com/user-attachments/assets/d7104947-7c0a-4670-9938-508a0a0c966b)

对于后端本地开发或部署到服务器，接口测试工具都可以请求到，但是前端无法访问，我不明白是什么原因。

**Comment by ronger-x** [comment]
本地开发时, 后端接口地址默认为 `BASE: 'http://localhost:8099/forest',`, 如修改了后端项目端口应修改为 `BASE: 'http://localhost:8080/forest',`

部署至生产环境应使用 nginx 等反向代理服务实现  /api -> /api/v1

**Comment by LiManyuan663** [comment]
好的，谢谢解答
