### ISSUE TITLE
rymcu.com部署的项目和当前项目的兼容性问题

### ISSUE THREAD

**Issue by Undertone0809** [rymcu/nebula#49]
我发现了一些问题在 https://rymcu.com/ 的网站上不会出现，但是我clone项目下来跑的时候就会遇到这些问题，是因为作者部署的版本和开源的版本有一些不同是吗？

**Comment by Undertone0809** [comment]
比如我发现下面这个提示在本地跑的时候不会出现，而是会由后端直接抛出Exception，我看到后端的部分好像有一些Exception还是没有处理的；其次，点击登陆按钮之后网站上面的loginLoading状态也会迅速变成false，但是在本地跑的时候因为没有做处理，会直接报500的提示，loginLoading状态也需要在10s后才变成false。

![image](https://user-images.githubusercontent.com/72488598/197359777-77fbd6f1-6468-44d5-a68c-2fd703a71fd6.png)

![image](https://user-images.githubusercontent.com/72488598/197359877-538950b1-6b23-4068-9a0c-85e7e7f7084a.png)

**Comment by ronger-x** [comment]
rymcu.com 部署的版本比当前 GitHub 上的版本低，GitHub 上的代码还在优化调整中，等到测试稳定了才会上线

1. 计划引入 nuxt/auth 替换掉当前登录/权限判断
2. 项目还没有一套统一的错误码并且还存在一些缺陷，有兴趣的话欢迎 PR

> [forest](https://github.com/rymcu/forest) 项目和[nebula](https://github.com/rymcu/nebula) 项目正在快速变化中，不建议生产使用
